# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: '0 19 * * *'


env:
  bot_webhook_url: ${{ secrets.BOT_WEBHOOK_URL }}
  channel_webhook_url: ${{ secrets.CHANNEL_WEBHOOK_URL }}
  smtp_port: ${{ secrets.SMTP_PORT }}
  sender_zoho_password: ${{ secrets.SENDER_ZOHO_PASSWORD }}
  sender_zoho_email: ${{ secrets.SENDER_ZOHO_EMAIL }}
  smtp_zoho_server: ${{ secrets.SMTP_ZOHO_SERVER }}


jobs:

  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Lint with flake8
        run: |
          # stop the build if there are Python syntax errors or undefined names
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

      - name: Run Scheduler
        run: |
          python utils/scheduler.py

    
